# Exercises for Session 7: Web Scraping 2

In session 6 you learned how to download the HTML string of a webpage. In this session you will learn how to locate the information you want in the HTML string. It requires an understanding of how HTML is structured and methods to navigate the structure. In the exercises below you will mainly use the package `BeautifulSoup` to navigate the HTML (read more about BeautifulSoup in the [documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)).

# Part 1: Parsing a table from HTML using BeautifulSoup.

In this exercise you will learn how to extract the information you want from a webpage's HTML. `BeautifulSoup` is a useful package in Python that makes it easy to navigate the HTML and find the information you are looking for. 

The purpose of the exercise is to extract the data that are available on this webpage: https://www.basketball-reference.com/leagues/NBA_2018.html

Before working with the exercise, you should watch the 2 videos (7.1 and 7.2) below. The type of data you shall scrape in the exercise is quite different from what you see in the video: In the video we scrape text from articles; in the exercise you will scrape tables and make them into pandas DataFrames. 
Keep in mind that the principles are completely identical: You need to locate the information in the HTML and then convert it to some meaningful data (it could be a text file or a dataframe)

(I might talk a bit slow in some of the videos. Remember that you can turn up the speed on Youtube)

> *Note:* In session 6 you learned how to send your name and email with your request and limit the rate of your calls. In the solutions for session 7 and 8, I have excluded it for clarity. Since we do not send that many request in these exercises, it is not an issue here. But you should always remember to limit the rate of your calls in your own scraping projects.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('gs0xktunF-g', width=640, height=360)

In [ ]:
YouTubeVideo('GSUw069jOo8', width=640, height=360)

> **Ex. 7.1.1:** Open https://www.basketball-reference.com/leagues/NBA_2018.html. Download the webpage's HTML as you have done before with `Requests`. We want to locate the conference standings of the Eastern Conference in the HTML. 

> Go to "Elements" in the Chrome Developer Tools and find the Eastern Conference table in the HTML. Use `BeautifulSoup` to parse the HTML, so you only have the HTML of the Eastern Conference table.

> *Hint:* What [tag name](https://www.w3schools.com/TAgs/default.asp) is used for tables? And what [attribute](https://www.w3schools.com/html/html_attributes.asp) identifies the table? Use it to select the table.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [1]:
### BEGIN SOLUTION
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

# Define our URL
url = 'https://www.basketball-reference.com/leagues/NBA_2018.html' 

# Connects to site
response = requests.get(url)

# Parse data with BeautifulSoup
soup = BeautifulSoup(response.content,'lxml')

# Identify table to scrape by inspecting site
table_node = soup.find(id = 'confs_standings_E')

In [2]:
table_node
### END SOLUTION

<table class="suppress_all sortable stats_table" data-cols-to-freeze=",1" id="confs_standings_E">
<caption>Conference Standings Table</caption>
<colgroup><col/><col/><col/><col/><col/><col/><col/><col/></colgroup>
<thead>
<tr>
<th aria-label="Eastern Conference" class="poptip sort_default_asc left" data-stat="team_name" scope="col">Eastern Conference</th>
<th aria-label="Wins" class="poptip right" data-stat="wins" data-tip="Wins" scope="col">W</th>
<th aria-label="Losses" class="poptip right" data-stat="losses" data-tip="Losses" scope="col">L</th>
<th aria-label="Win-Loss Percentage" class="poptip right" data-stat="win_loss_pct" data-tip="Win-Loss Percentage" scope="col">W/L%</th>
<th aria-label="GB" class="poptip sort_default_asc right" data-stat="gb" data-tip="Games Behind" scope="col">GB</th>
<th aria-label="Points Per Game" class="poptip right" data-stat="pts_per_g" data-tip="Points Per Game" scope="col">PS/G</th>
<th aria-label="Opponent Points Per Game" class="poptip right" data-stat="opp_pts_per_g" data-tip="Opponent Points Per Game" scope="col">PA/G</th>
<th aria-label="Simple Rating System" class="poptip right" data-stat="srs" data-tip="Simple Rating System; a team rating that takes into account average point differential and strength of schedule. The rating is denominated in points above/below average, where zero is average." scope="col">SRS</th>
</tr>
</thead>
<tbody><tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/TOR/2018.html">Toronto Raptors</a>*</th><td class="right" data-stat="wins">59</td><td class="right" data-stat="losses">23</td><td class="right" data-stat="win_loss_pct">.720</td><td class="right" data-stat="gb">â€”</td><td class="right" data-stat="pts_per_g">111.7</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">7.29</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BOS/2018.html">Boston Celtics</a>*</th><td class="right" data-stat="wins">55</td><td class="right" data-stat="losses">27</td><td class="right" data-stat="win_loss_pct">.671</td><td class="right" data-stat="gb">4.0</td><td class="right" data-stat="pts_per_g">104.0</td><td class="right" data-stat="opp_pts_per_g">100.4</td><td class="right" data-stat="srs">3.23</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/PHI/2018.html">Philadelphia 76ers</a>*</th><td class="right" data-stat="wins">52</td><td class="right" data-stat="losses">30</td><td class="right" data-stat="win_loss_pct">.634</td><td class="right" data-stat="gb">7.0</td><td class="right" data-stat="pts_per_g">109.8</td><td class="right" data-stat="opp_pts_per_g">105.3</td><td class="right" data-stat="srs">4.30</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CLE/2018.html">Cleveland Cavaliers</a>*</th><td class="right" data-stat="wins">50</td><td class="right" data-stat="losses">32</td><td class="right" data-stat="win_loss_pct">.610</td><td class="right" data-stat="gb">9.0</td><td class="right" data-stat="pts_per_g">110.9</td><td class="right" data-stat="opp_pts_per_g">109.9</td><td class="right" data-stat="srs">0.59</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/IND/2018.html">Indiana Pacers</a>*</th><td class="right" data-stat="wins">48</td><td class="right" data-stat="losses">34</td><td class="right" data-stat="win_loss_pct">.585</td><td class="right" data-stat="gb">11.0</td><td class="right" data-stat="pts_per_g">105.6</td><td class="right" data-stat="opp_pts_per_g">104.2</td><td class="right" data-stat="srs">1.18</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIA/2018.html">Miami Heat</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">102.9</td><td class="right" data-stat="srs">0.15</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIL/2018.html">Milwaukee Bucks</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">106.5</td><td class="right" data-stat="opp_pts_per_g">106.8</td><td class="right" data-stat="srs">-0.45</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/WAS/2018.html">Washington Wizards</a>*</th><td class="right" data-stat="wins">43</td><td class="right" data-stat="losses">39</td><td class="right" data-stat="win_loss_pct">.524</td><td class="right" data-stat="gb">16.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">106.0</td><td class="right" data-stat="srs">0.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/DET/2018.html">Detroit Pistons</a></th><td class="right" data-stat="wins">39</td><td class="right" data-stat="losses">43</td><td class="right" data-stat="win_loss_pct">.476</td><td class="right" data-stat="gb">20.0</td><td class="right" data-stat="pts_per_g">103.8</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">-0.26</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHO/2018.html">Charlotte Hornets</a></th><td class="right" data-stat="wins">36</td><td class="right" data-stat="losses">46</td><td class="right" data-stat="win_loss_pct">.439</td><td class="right" data-stat="gb">23.0</td><td class="right" data-stat="pts_per_g">108.2</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">0.07</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/NYK/2018.html">New York Knicks</a></th><td class="right" data-stat="wins">29</td><td class="right" data-stat="losses">53</td><td class="right" data-stat="win_loss_pct">.354</td><td class="right" data-stat="gb">30.0</td><td class="right" data-stat="pts_per_g">104.5</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">-3.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BRK/2018.html">Brooklyn Nets</a></th><td class="right" data-stat="wins">28</td><td class="right" data-stat="losses">54</td><td class="right" data-stat="win_loss_pct">.341</td><td class="right" data-stat="gb">31.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">110.3</td><td class="right" data-stat="srs">-3.67</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHI/2018.html">Chicago Bulls</a></th><td class="right" data-stat="wins">27</td><td class="right" data-stat="losses">55</td><td class="right" data-stat="win_loss_pct">.329</td><td class="right" data-stat="gb">32.0</td><td class="right" data-stat="pts_per_g">102.9</td><td class="right" data-stat="opp_pts_per_g">110.0</td><td class="right" data-stat="srs">-6.84</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ORL/2018.html">Orlando Magic</a></th><td class="right" data-stat="wins">25</td><td class="right" data-stat="losses">57</td><td class="right" data-stat="win_loss_pct">.305</td><td class="right" data-stat="gb">34.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.2</td><td class="right" data-stat="srs">-4.92</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ATL/2018.html">Atlanta Hawks</a></th><td class="right" data-stat="wins">24</td><td class="right" data-stat="losses">58</td><td class="right" data-stat="win_loss_pct">.293</td><td class="right" data-stat="gb">35.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.8</td><td class="right" data-stat="srs">-5.30</td></tr>
</tbody></table>

Now you have located the table. Inspect the table in "Elements" in Chrome Developer Tools and notice how a table is written in HTML. Ask yourself: Which tag names can be used to locate rows? And columns/headers? In the following exercises we use these tag names to download the data in the table.

> **Ex. 7.1.2:** Use `find_all` to search for the columns/headers of the table. Loop through all the columns to extract the text of each column. Store the columns in a list.

> *Hint:* Notice that the table consists of a thead and tbody. The columns are located in the thead.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [2]:
### BEGIN SOLUTION
# Get the columns in a list
columns_html = table_node.thead.find_all('th')
# Extract the text
columns = [col.text for col in columns_html] #Use a list comprehension to make extract the text (If you have used a for loop instead, it is also just fine!)
### END SOLUTION

> **Ex. 7.1.3:** Now locate the rows (the rows are in tbody). Use `find_all` to locate all rows in the table and store in a list called *rows_list*.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [4]:
### BEGIN SOLUTION
rows_list = table_node.tbody.find_all('tr')

In [5]:
rows_list
### END SOLUTION

[<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/TOR/2018.html">Toronto Raptors</a>*</th><td class="right" data-stat="wins">59</td><td class="right" data-stat="losses">23</td><td class="right" data-stat="win_loss_pct">.720</td><td class="right" data-stat="gb">â€”</td><td class="right" data-stat="pts_per_g">111.7</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">7.29</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BOS/2018.html">Boston Celtics</a>*</th><td class="right" data-stat="wins">55</td><td class="right" data-stat="losses">27</td><td class="right" data-stat="win_loss_pct">.671</td><td class="right" data-stat="gb">4.0</td><td class="right" data-stat="pts_per_g">104.0</td><td class="right" data-stat="opp_pts_per_g">100.4</td><td class="right" data-stat="srs">3.23</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/PHI/2018.html">Philadelphia 76ers</a>*</th><td class="right" data-stat="wins">52</td><td class="right" data-stat="losses">30</td><td class="right" data-stat="win_loss_pct">.634</td><td class="right" data-stat="gb">7.0</td><td class="right" data-stat="pts_per_g">109.8</td><td class="right" data-stat="opp_pts_per_g">105.3</td><td class="right" data-stat="srs">4.30</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CLE/2018.html">Cleveland Cavaliers</a>*</th><td class="right" data-stat="wins">50</td><td class="right" data-stat="losses">32</td><td class="right" data-stat="win_loss_pct">.610</td><td class="right" data-stat="gb">9.0</td><td class="right" data-stat="pts_per_g">110.9</td><td class="right" data-stat="opp_pts_per_g">109.9</td><td class="right" data-stat="srs">0.59</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/IND/2018.html">Indiana Pacers</a>*</th><td class="right" data-stat="wins">48</td><td class="right" data-stat="losses">34</td><td class="right" data-stat="win_loss_pct">.585</td><td class="right" data-stat="gb">11.0</td><td class="right" data-stat="pts_per_g">105.6</td><td class="right" data-stat="opp_pts_per_g">104.2</td><td class="right" data-stat="srs">1.18</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIA/2018.html">Miami Heat</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">102.9</td><td class="right" data-stat="srs">0.15</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIL/2018.html">Milwaukee Bucks</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">106.5</td><td class="right" data-stat="opp_pts_per_g">106.8</td><td class="right" data-stat="srs">-0.45</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/WAS/2018.html">Washington Wizards</a>*</th><td class="right" data-stat="wins">43</td><td class="right" data-stat="losses">39</td><td class="right" data-stat="win_loss_pct">.524</td><td class="right" data-stat="gb">16.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">106.0</td><td class="right" data-stat="srs">0.53</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/DET/2018.html">Detroit Pistons</a></th><td class="right" data-stat="wins">39</td><td class="right" data-stat="losses">43</td><td class="right" data-stat="win_loss_pct">.476</td><td class="right" data-stat="gb">20.0</td><td class="right" data-stat="pts_per_g">103.8</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">-0.26</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHO/2018.html">Charlotte Hornets</a></th><td class="right" data-stat="wins">36</td><td class="right" data-stat="losses">46</td><td class="right" data-stat="win_loss_pct">.439</td><td class="right" data-stat="gb">23.0</td><td class="right" data-stat="pts_per_g">108.2</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">0.07</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/NYK/2018.html">New York Knicks</a></th><td class="right" data-stat="wins">29</td><td class="right" data-stat="losses">53</td><td class="right" data-stat="win_loss_pct">.354</td><td class="right" data-stat="gb">30.0</td><td class="right" data-stat="pts_per_g">104.5</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">-3.53</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BRK/2018.html">Brooklyn Nets</a></th><td class="right" data-stat="wins">28</td><td class="right" data-stat="losses">54</td><td class="right" data-stat="win_loss_pct">.341</td><td class="right" data-stat="gb">31.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">110.3</td><td class="right" data-stat="srs">-3.67</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHI/2018.html">Chicago Bulls</a></th><td class="right" data-stat="wins">27</td><td class="right" data-stat="losses">55</td><td class="right" data-stat="win_loss_pct">.329</td><td class="right" data-stat="gb">32.0</td><td class="right" data-stat="pts_per_g">102.9</td><td class="right" data-stat="opp_pts_per_g">110.0</td><td class="right" data-stat="srs">-6.84</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ORL/2018.html">Orlando Magic</a></th><td class="right" data-stat="wins">25</td><td class="right" data-stat="losses">57</td><td class="right" data-stat="win_loss_pct">.305</td><td class="right" data-stat="gb">34.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.2</td><td class="right" data-stat="srs">-4.92</td></tr>,
 <tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ATL/2018.html">Atlanta Hawks</a></th><td class="right" data-stat="wins">24</td><td class="right" data-stat="losses">58</td><td class="right" data-stat="win_loss_pct">.293</td><td class="right" data-stat="gb">35.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.8</td><td class="right" data-stat="srs">-5.30</td></tr>]

> **Ex. 7.1.4:** Loop through all rows in *rows_list* and extract the values. 

> *Hint:* Since the values in a row have different tags ("th" or "tr") we cannot use `find_all` to go through all values (`find_all` is used when the tag is the same). Instead we can use `.children` to get all values (/children) in each row. 
> 
> 1. Loop through the values in each row with a `for loop` to get all the values of the row and store in a list (use `append` to append to list).
>
> 2. Once you have constructed such a loop, you can construct another for loop around it that loops through all the rows in *rows_list*. Your outcome should be a list of the lists of all the row values (again use `append` to do this).
> - Your outcome should look like this: 
> 
> ```[['Toronto Raptors*', '59', '23', '.720', 'â€”', '111.7', '103.9', '7.29'],
 ['Boston Celtics*', '55', '27', '.671', '4.0', '104.0', '100.4', '3.23'],
 ...]```

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [6]:
### BEGIN SOLUTION
data = []
for row_node in rows_list:
    row = []
    for child in row_node.children:
        row.append(child.text)
    data.append(row)

In [7]:
data
### END SOLUTION

[['Toronto Raptors*', '59', '23', '.720', 'â€”', '111.7', '103.9', '7.29'],
 ['Boston Celtics*', '55', '27', '.671', '4.0', '104.0', '100.4', '3.23'],
 ['Philadelphia 76ers*', '52', '30', '.634', '7.0', '109.8', '105.3', '4.30'],
 ['Cleveland Cavaliers*', '50', '32', '.610', '9.0', '110.9', '109.9', '0.59'],
 ['Indiana Pacers*', '48', '34', '.585', '11.0', '105.6', '104.2', '1.18'],
 ['Miami Heat*', '44', '38', '.537', '15.0', '103.4', '102.9', '0.15'],
 ['Milwaukee Bucks*', '44', '38', '.537', '15.0', '106.5', '106.8', '-0.45'],
 ['Washington Wizards*', '43', '39', '.524', '16.0', '106.6', '106.0', '0.53'],
 ['Detroit Pistons', '39', '43', '.476', '20.0', '103.8', '103.9', '-0.26'],
 ['Charlotte Hornets', '36', '46', '.439', '23.0', '108.2', '108.0', '0.07'],
 ['New York Knicks', '29', '53', '.354', '30.0', '104.5', '108.0', '-3.53'],
 ['Brooklyn Nets', '28', '54', '.341', '31.0', '106.6', '110.3', '-3.67'],
 ['Chicago Bulls', '27', '55', '.329', '32.0', '102.9', '110.0', '-6.84'],
 ['Orlando Magic', '25', '57', '.305', '34.0', '103.4', '108.2', '-4.92'],
 ['Atlanta Hawks', '24', '58', '.293', '35.0', '103.4', '108.8', '-5.30']]

> **Ex. 7.1.5:** Combine your answers to **Ex. 7.1.2-4** to make a function called *parse_html_table* that creates a dataframe from the HTML.

> *Hint:* The only new thing you need to do is to create a dataframe out of the list of lists you made in ex. 7.1.4.
>
> Try to search on google to figure out how to make a dataframe out of a list of lists.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [3]:
### BEGIN SOLUTION
def parse_html_table(table_node):
    # Get the columns in a list
    columns_html = table_node.thead.find_all('th')
    # Extract the text
    columns = [col.text for col in columns_html]

    rows_list = table_node.tbody.find_all('tr')

    data = []
    for row_node in rows_list:
        row = []
        for child in row_node.children:
            row.append(child.text)
        data.append(row)
    df = pd.DataFrame(data,columns=columns)
    return df

In [53]:
df = parse_html_table(table_node)

In [54]:
df
### END SOLUTION

      Eastern Conference   W   L  W/L%    GB   PS/G   PA/G    SRS
0       Toronto Raptors*  59  23  .720     â€”  111.7  103.9   7.29
1        Boston Celtics*  55  27  .671   4.0  104.0  100.4   3.23
2    Philadelphia 76ers*  52  30  .634   7.0  109.8  105.3   4.30
3   Cleveland Cavaliers*  50  32  .610   9.0  110.9  109.9   0.59
4        Indiana Pacers*  48  34  .585  11.0  105.6  104.2   1.18
5            Miami Heat*  44  38  .537  15.0  103.4  102.9   0.15
6       Milwaukee Bucks*  44  38  .537  15.0  106.5  106.8  -0.45
7    Washington Wizards*  43  39  .524  16.0  106.6  106.0   0.53
8        Detroit Pistons  39  43  .476  20.0  103.8  103.9  -0.26
9      Charlotte Hornets  36  46  .439  23.0  108.2  108.0   0.07
10       New York Knicks  29  53  .354  30.0  104.5  108.0  -3.53
11         Brooklyn Nets  28  54  .341  31.0  106.6  110.3  -3.67
12         Chicago Bulls  27  55  .329  32.0  102.9  110.0  -6.84
13         Orlando Magic  25  57  .305  34.0  103.4  108.2  -4.92
14         Atlanta Hawks  24  58  .293  35.0  103.4  108.8  -5.30

> **Ex. 7.1.6:** Now instead of only looking at the Eastern Conference standings table we want to get the data of all tables on the webpage. 

> 1. Locate all tables on the page by using `find_all` to search for the table tag name (```<table>```). Name the list of tables as "tables".

> 2. Use your function *parse_html_table* to loop through all tables in "tables" and parse their data. Store all the dataframes in a list.
>
> *Hint:* You need to make a for loop with two lines of code in it: 
>- in the first line you use your function *parse_html_table* to make a dataframe, 
>- and in the second line you append the dataframe to an empty list of dataframes that you have made before the loop.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [4]:
### BEGIN SOLUTION
tables = soup.find_all('table') #Locate all table nodes
dfs = []
for i in range(3): #"len(tables)" instead of 3 to get all tables
    table = parse_html_table(tables[i]) #Apply parse_html_table function
    dfs.append(table) # store table in a list

In [69]:
dfs[0]
### END SOLUTION

      Eastern Conference   W   L  W/L%    GB   PS/G   PA/G    SRS
0       Toronto Raptors*  59  23  .720     â€”  111.7  103.9   7.29
1        Boston Celtics*  55  27  .671   4.0  104.0  100.4   3.23
2    Philadelphia 76ers*  52  30  .634   7.0  109.8  105.3   4.30
3   Cleveland Cavaliers*  50  32  .610   9.0  110.9  109.9   0.59
4        Indiana Pacers*  48  34  .585  11.0  105.6  104.2   1.18
5            Miami Heat*  44  38  .537  15.0  103.4  102.9   0.15
6       Milwaukee Bucks*  44  38  .537  15.0  106.5  106.8  -0.45
7    Washington Wizards*  43  39  .524  16.0  106.6  106.0   0.53
8        Detroit Pistons  39  43  .476  20.0  103.8  103.9  -0.26
9      Charlotte Hornets  36  46  .439  23.0  108.2  108.0   0.07
10       New York Knicks  29  53  .354  30.0  104.5  108.0  -3.53
11         Brooklyn Nets  28  54  .341  31.0  106.6  110.3  -3.67
12         Chicago Bulls  27  55  .329  32.0  102.9  110.0  -6.84
13         Orlando Magic  25  57  .305  34.0  103.4  108.2  -4.92
14         Atlanta Hawks  24  58  .293  35.0  103.4  108.8  -5.30

> **Ex. 7.1.7 (extra) :** `Pandas` has a built-in function called `read_html` that does the exact same thing as you have just learned. Compare your results to this Pandas implementation ([pd.read_html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_html.html)). 

> *Note:* It may seem like a lot of work to go through all the steps when there is a function that does it already. However, the purpose of the exercises above is to prepare you for your own scraping challenges, and that is best done by hard coding everything. It is also important to note that scraping is no exact science, so there may be websites where the general function `read_html` does not work. In those cases, you should be able to build your own scraper.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [70]:
### BEGIN SOLUTION
url = 'https://www.basketball-reference.com/leagues/NBA_2018.html' # Link to the website
dfs = pd.read_html(url) # Parses all tables found on the page.
dfs[0]
### END SOLUTION

      Eastern Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0       Toronto Raptors*  59  23  0.720     â€”  111.7  103.9  7.29
1        Boston Celtics*  55  27  0.671   4.0  104.0  100.4  3.23
2    Philadelphia 76ers*  52  30  0.634   7.0  109.8  105.3  4.30
3   Cleveland Cavaliers*  50  32  0.610   9.0  110.9  109.9  0.59
4        Indiana Pacers*  48  34  0.585  11.0  105.6  104.2  1.18
5            Miami Heat*  44  38  0.537  15.0  103.4  102.9  0.15
6       Milwaukee Bucks*  44  38  0.537  15.0  106.5  106.8 -0.45
7    Washington Wizards*  43  39  0.524  16.0  106.6  106.0  0.53
8        Detroit Pistons  39  43  0.476  20.0  103.8  103.9 -0.26
9      Charlotte Hornets  36  46  0.439  23.0  108.2  108.0  0.07
10       New York Knicks  29  53  0.354  30.0  104.5  108.0 -3.53
11         Brooklyn Nets  28  54  0.341  31.0  106.6  110.3 -3.67
12         Chicago Bulls  27  55  0.329  32.0  102.9  110.0 -6.84
13         Orlando Magic  25  57  0.305  34.0  103.4  108.2 -4.92
14         Atlanta Hawks  24  58  0.293  35.0  103.4  108.8 -5.30